// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNotecard struct {
	Title string `json:"title"`
	Entry string `json:"entry"`
}

type NewSection struct {
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle"`
	NotecardID []string `json:"notecardID"`
}

type Notecard struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Entry string `json:"entry"`
}

type Section struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	SubTitle  string      `json:"subTitle"`
	NoteCards []*Notecard `json:"noteCards"`
}
